name: Daily Data Update

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 00:00 KST (UTC 15:00)
  workflow_dispatch:

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Flask API Update
        run: |
          curl -X POST "https://kbo-prediction.onrender.com/force-update"
